version: "3.8"
name: tg_bot

services:
  bot:
    restart: no
    cpu_count: 1
    shm_size: 128mb
    depends_on:
      db:
        condition: service_healthy
        restart: true
    build:
      dockerfile_inline: |
        FROM python:3.12-alpine
        WORKDIR /opt/tg_bot/
        COPY bot.conf /opt/tg_bot/
        COPY python_bot.py /opt/tg_bot/
        COPY requirements.txt /opt/tg_bot/
        RUN pip install --no-cache-dir -r requirements.txt
        CMD python ./python_bot.py

  db:
    image: postgres:16.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/lib/postgresql/log
    env_file:
      - path: ./default.env
        required: true
      - path: ./custom.env
        required: false
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    ports:
      - "8000:80"

volumes:
  postgres_data:
    name: PG_DATA_VOLUME
  postgres_logs:
    name: PG_LOG_VOLUME